config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :properties
  resources :order_details
  resources :orders
  resources :customer
  resources :item_categories
  resources :menus
  resources :categories
  get "reports", to: "orders#report"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :menu

  validates :order_id, presence: true
  validates :menu_id, presence: true
  validates :quantity, presence: true, numericality: true

  before_create :find_menu_price

  def find_menu_price
    Menu.by_id(self.menu_id).each do |menu|
      self.price = menu.price.to_i
    end
  end

  def find_menu_name
    Menu.by_id(self.menu_id).each do |menu|
      return menu.name
    end
  end

  def count_total_price
    total = self.quantity * self.price
  end

  def self.by_order_id(id)
    where("order_id = #{id}").order(:order_id)
  end

end

app/controllers/order_details_controller.rb
class OrderDetailsController < ApplicationController
  before_action :set_order_detail, only: %i[ show edit update destroy ]

  def index
    @order_details = params[:id].nil? ? OrderDetail.all : OrderDetail.by_order_id(params[:id])
  end

  def show
  end

  def new
    @order_detail = OrderDetail.new
  end

  def edit
  end

  def create
    @order_detail = OrderDetail.new(order_detail_params)

    respond_to do |format|
      if @order_detail.save
        format.html { redirect_to order_detail_url(@order_detail), notice: "Order detail was successfully created." }
        format.json { render :show, status: :created, location: @order_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @order_detail.update(order_detail_params)
        format.html { redirect_to order_detail_url(@order_detail), notice: "Order detail was successfully updated." }
        format.json { render :show, status: :ok, location: @order_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order_detail.destroy

    respond_to do |format|
      format.html { redirect_to order_details_url, notice: "Order detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_order_detail
      @order_detail = OrderDetail.find(params[:id])
    end

    def order_detail_params
      params.fetch(:order_detail, {}).permit(:order_id, :menu_id, :price, :quantity)
    end
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/views/order_details/_form.html.erb
<%= form_with(model: order_detail) do |form| %>
  <% if order_detail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order_detail.errors.count, "error") %> prohibited this order_detail from being saved:</h2>

      <ul>
        <% order_detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    
  <%= form.hidden_field :order_id, class: "form-control", value: session[:order_id] %>
      
  <div class="mb-3 row">
    <%= form.label :menu, style: "display: block", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.select :menu_id, Menu.all.pluck(:name,:id),{prompt:'Select Menu'},{class: "form-control", id: "menu"}%>
    </div>
  </div>

  <div class="mb-3 row">
    <%= form.label :quantity, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-1">
      <%= form.text_field :quantity, class: "form-control" %>
    </div>
  </div>
        
  <div>
    <%= form.submit %>
  </div>
    
<% end %>

app/views/order_details/_order_detail.html.erb
<div id="<%= dom_id order_detail %>">
  <p>
    <strong>Menu id :</strong>
    <%= order_detail.menu_id %>
  </p>

  <p>
    <strong>Quantity :</strong>
    <%= order_detail.quantity %>
  </p>

  <p>
    <strong>Price :</strong>
    <%= order_detail.price %>
  </p>
</div>

app/views/order_details/edit.html.erb
<h1>Editing order detail</h1>

<%= render "form", order_detail: @order_detail %>

<br>

<div>
  <%= link_to "Show this order detail", @order_detail %> |
  <%= link_to "Back to order details", order_details_path %>
</div>

app/views/order_details/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Order details</h1>

<div class="table">
  <table class="table table-bordered">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Menu</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Total</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @order_details.each do |order_detail| %>
        <tr>
          <td><%= order_detail.find_menu_name %></td>
          <td><%= order_detail.price %></td>
          <td><%= order_detail.quantity %></td>
          <td><%= order_detail.count_total_price %></td>
          <td><%= link_to "Show this order detail", order_detail %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/order_details/new.html.erb
<h1>New order detail</h1>

<%= render "form", order_detail: @order_detail %>

<br>

<div>
  <%= link_to "Back to order details", order_details_path %>
</div>

app/views/order_details/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order_detail %>

<div>
  <%= link_to "Edit this order detail", edit_order_detail_path(@order_detail) %> |
  <%= link_to "Back to order details", order_details_path %> |
  <%= link_to "Back to orders", orders_path %>

  <%= button_to "Destroy this order detail", @order_detail, method: :delete %>
</div>