config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :properties
  resources :order_details
  resources :orders
  resources :customer
  resources :item_categories
  resources :menus
  resources :categories
  get "reports", to: "orders#report"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details

  validates :customer_id, presence: true
  
  def find_customer
    Customer.by_id(self.customer_id).each do |customer|
      return customer.email
    end
  end

  def self.report_today
    where("order_date LIKE ?", "#{Date.current}%").order(:id)
  end

  def find_by_email(email)
    where("email LIKE ?", "#{email}%").order(:id)
  end
  
  def count_total_price
    total = []
    OrderDetail.by_order_id(self.id).each do |detail_order|
      total << detail_order.quantity * detail_order.price
    end
    return total.inject(0){|sum,x| sum + x }
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  def index
    @orders = Order.all
  end

  def show
  end

  def new
    @order = Order.new
  end

  def edit
  end

  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def report
    @reports = params[:email].nil? ? Order.report_today : Order.find_by_email(params[:email])
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.fetch(:order, {}).permit(:customer_id, :order_date, :status)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :customer_id, style: "display: block" %>
    <%= form.select :customer_id, Customer.all.pluck(:email,:id),{prompt:'Select Customer'},{class: "form-control"}%>
  </div>

  <div class="mb-3">
      <%= form.label :order_date, class: "form-label" %>
      <%= form.date_field :order_date, class: "form-control" %>
  </div>
        
  <div class="mb-3">
    <%= form.label :status, class: "form-label" %>
    <%= form.select :status, ['NEW', 'PAID', 'CANCELED'], {prompt:'Select Status'}, {class: "form-control"} %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_form_edit.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :customer_id, style: "display: block" %>
    <%= form.select :customer_id, Customer.all.pluck(:email,:id),{prompt:'Select Customer'},{class: "form-control"}%>
  </div>

  <div class="mb-3">
      <%= form.label :order_date, class: "form-label" %>
      <%= form.text_field :order_date, class: "form-control" %>
  </div>
        
  <div class="mb-3">
    <%= form.label :status, class: "form-label" %>
    <%= form.select :status, ['NEW', 'PAID', 'CANCELED'], {prompt:'Select Status'}, {class: "form-control"} %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  
  <% session[:order_id] = order.id %>
    
  <p>
    <strong>Order Date:</strong>
    <%= order.order_date %>
  </p>

  <p>
    <strong>Customer:</strong>
    <%= order.customer_id %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= order.status %>
  </p>
</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form_edit", order: @order %>
<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders <%= link_to "New order", new_order_path, class: "btn btn-success" %> </h1>

<div class="table">
  <table class="table table-bordered">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Customer Email</th>
        <th scope="col">Status</th>
        <th scope="col">Total</th>
        <th scope="col" colspan="3">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.order_date %></td>
          <td><%= order.find_customer %></td>
          <td><%= order.status %></td>
          <td><%= order.count_total_price %></td>
          <td><%= link_to "Information", order %></td>
          <td><%= link_to "Add Menu Order", order %></td>
          <td><%= link_to "Order Menu Details", "order_details?id=#{order.id}"  %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/report.html.erb
<p style="color: green"><%= notice %></p>

<h1>Report Order <%= Date.current %></h1>

<div class="table">
  <table class="table table-bordered">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Customer Email</th>
        <th scope="col">Status</th>
        <th scope="col">Total</th>
      </tr>
    </thead>
    <tbody>
      <% @reports.each do |report| %>
        <tr>
          <td><%= report.order_date %></td>
          <td><%= report.find_customer %></td>
          <td><%= report.status %></td>
          <td><%= report.count_total_price %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order %>

<div>
  <%= link_to "Edit this order", edit_order_path(@order) %> |
  <%= link_to "Back to orders", orders_path %> | 
  <%= link_to "Add Order Menu", new_order_detail_path %>

  <%= button_to "Destroy this order", @order, method: :delete %>
</div>